name: rtools
channels:
  - conda-forge
  - bioconda
dependencies:
  - Python=3.6.*
  - pip=19.2.3
  - ca-certificates=2019.11.28
  - openssl=1.1.1d
  - quast=5.0.2
  - augustus=3.3.3
  - busco=3.0.2  # BUSCO has an R dependency
  - circos=0.69.8
  - hmmer=3.1b2
  - blast=2.2.31
  - htslib=1.9
  - perl=5.26.2
  - r-base=3.5.1

