name: pbtools
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=2.7.*
  - python-consensuscore2=3.4.1
  - genomicconsensus=2.3.3
  - pbccs=3.4.1
  - pbbam=1.0.6
  - pbmm2=1.1.0
  - pbcoretools=0.2.4
  - hap.py=0.3.10