name: dipassm
channels:
  - conda-forge
  - bioconda
dependencies:
  - Python=3.6.*
  - Snakemake=5.4.0
  - aria2=1.34.0
  - minimap2=2.16
  - mummer4
  - sambamba=0.6.8
  - samtools=1.9
  - bcftools=1.9
  - wtdbg=2.3
  - pbgzip
  - pigz=2.4
  - pip:
    - git+https://bitbucket.org/whatshap/whatshap
