name: dipassm
channels:
  - conda-forge
  - bioconda
  - r
dependencies:
  - Python=3.6.*
  - pip=19.2.3
  - wget=1.19.4
  - openssl=1.0.2t
  - singularity=3.0.1
  - numpy=1.17.1
  - matplotlib=3.1.1
  - Snakemake=5.8.1
  - aria2=1.34.0
  - bwa=0.7.17
  - minimap2=2.17
  - pilon=1.23
  - quast=5.0.2
  - mummer4
  - busco=3.0.2
  - sambamba=0.6.6  # DO NOT UPDATE: github.com/biod/sambamba/issues/393
  - samtools=1.9
  - bamtools=2.5.1
  - bedtools=2.29.0
  - bedops=2.4.37
  - bcftools=1.9
  - fastqc=0.11.8
  - freebayes=1.3.1
  - longshot=v0.3.5
  - wtdbg=2.5
  - flye=2.6
  - racon=1.4.10
  - pbgzip
  - pigz=2.4
  - drmaa=0.7.9
  - libxml2=2.9.9
  - r-xml=3.98_1.20
  - r-base<3.6
  - r-devtools=2.2.1
  - r-usethis=1.5.1
  - r-withr=2.1.2
  - r-igraph=1.2.4.1
  - r-zoo=1.8_6
  - r-cluster=2.1.0
  - r-doparallel=1.0.15
  - r-foreach=1.4.7
  - r-biocmanager=1.30.7
  - bioconductor-rtracklayer=1.42.1
  - bioconductor-rhtslib=1.14.1
  - bioconductor-bamsignals=1.14.0
  - pip:
    - git+https://bitbucket.org/whatshap/whatshap
