name: rdga
channels:
  - conda-forge
  - bioconda
  - r
dependencies:
  - Python=3.6.*
  - pip=19.2.3
  - wget=1.19.4
  - openssl=1.0.2t
  - gxx_impl_linux-64=7.3.0
  - gxx_linux-64=7.3.0
  - ld_impl_linux-64=2.33.1
  - libblas=3.8.0
  - libcblas=3.8.0
  - liblapack=3.8.0
  - libopenblas=0.3.6
  - libgfortran-ng=7.3.0
  - libgcc-ng=9.1.0
  - libstdcxx-ng=9.1.0
  - libxml2=2.9.9
  - libcurl=7.64.0
  - lp_solve=5.5.2.5
  - openblas=0.3.6
  - make=4.2.1
  - htslib=1.9
  - r-base<3.6
  - r-curl=4.2
  - r-xml=3.98_1.20
  - r-devtools=2.2.1
  - r-usethis=1.5.1
  - r-withr=2.1.2
  - r-igraph=1.2.4.1
  - r-zoo=1.8_6
  - r-cluster=2.1.0
  - r-doparallel=1.0.15
  - r-foreach=1.4.7
  - r-biocmanager=1.30.7
  - bioconductor-rtracklayer=1.42.1
  - bioconductor-rhtslib=1.14.1
  - bioconductor-bamsignals=1.14.0
