name: dipassm
channels:
  - conda-forge
  - bioconda
dependencies:
  - Python=3.6.*
  - pip=19.2.3
  - wget=1.19.4
  - openssl=1.0.2t
  - gxx_impl_linux-64=7.3.0
  - gxx_linux-64=7.3.0
  - ld_impl_linux-64=2.33.1
  - libblas=3.8.0
  - libcblas=3.8.0
  - liblapack=3.8.0
  - libopenblas=0.3.6
  - libgfortran-ng=7.3.0
  - libgcc-ng=9.1.0
  - libstdcxx-ng=9.1.0
  - libxml2=2.9.9
  - libcurl=7.64.0
  - lp_solve=5.5.2.5
  - openblas=0.3.6
  - make=4.2.1
  - numpy=1.17.1
  - matplotlib=3.1.1
  - Snakemake=5.8.1
  - aria2=1.34.0
  - bwa=0.7.17
  - minimap2=2.17
  - mummer4
  - sambamba=0.6.6  # DO NOT UPDATE: github.com/biod/sambamba/issues/393
  - htslib=1.9
  - samtools=1.9
  - bamtools=2.5.1
  - bedtools=2.29.0
  - bedops=2.4.37
  - bcftools=1.9
  - fastqc=0.11.8
  - freebayes=1.3.1
  - longshot=v0.3.5
  - wtdbg=2.5
  - flye=2.6
  - racon=1.4.10
  - pbgzip
  - pigz=2.4
  - drmaa=0.7.9
  - pip:
    - git+https://bitbucket.org/whatshap/whatshap
