# Default runtime profile for temp. infrastructure / PORTIA

directory: /TM_beegfs/projects/diploid-genome-assembly/pebert
cores: 18
latency-wait: 5
keep-going: True
rerun-incomplete: True
restart-times: 1
resources:
  mem_mb=96256
