
notify: False
notify_email: pebert@mpi-inf.mpg.de


ref_genome:
  hg38_decoy_hla:
    url: ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/technical/reference/GRCh38_reference_genome/GRCh38_full_analysis_set_plus_decoy_hla.fa
    name: GRCh38_decoy_hla.fa


read_files:
  ucsc_round2:
    file1:
      url: https://s3-us-west-2.amazonaws.com/human-pangenomics/GM24385/nanopore/GM24385_1.fastq.gz
      name: HG002.ucsc2.ont.part1
    file2:
      url: https://s3-us-west-2.amazonaws.com/human-pangenomics/GM24385/nanopore/GM24385_2.fastq.gz
      name: HG002.ucsc2.ont.part2
    file3:
      url: https://s3-us-west-2.amazonaws.com/human-pangenomics/GM24385/nanopore/GM24385_3.fastq.gz
      name: HG002.ucsc2.ont.part3
  giab:
    file1:
      url: ftp://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/data/AshkenazimTrio/HG002_NA24385_son/Ultralong_OxfordNanopore/combined_2018-05-18/combined_2018-05-18.fastq.gz
      name: HG002.giab.ont-ul.201805
    file2:
      url: ftp://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/data/AshkenazimTrio/HG002_NA24385_son/Ultralong_OxfordNanopore/combined_2018-08-10/combined_2018-08-10.fastq.gz
      name: HG002.giab.ont-ul.201808
