# Default runtime profile for DEEP infrastructure / SGE cluster

directory: /TL/deep/fhgfs/projects/pebert/cbi/diploid-assembly
drmaa-log-dir: /TL/deep/fhgfs/projects/pebert/cbi/diploid-assembly/log/cluster_jobs
drmaa: " {cluster.clusterSpec}"
jobname: "SMK{jobid}_{name}"
cluster-config: /home/pebert/work/code/github/project-diploid-assembly/environment/snakemake/cluster/deep/deep_cluster.json
local-cores: 4
jobs: 200
latency-wait: 1
keep-going: True
rerun-incomplete: False
restart-times: 1