# Default runtime profile for TM infrastructure / D3 compute server

directory: /MMCI/TM/scratch/pebert/diploid_assembly
cores: 24
latency-wait: 10
keep-going: True
rerun-incomplete: True
restart-times: 0
