# Default runtime profile for TM infrastructure / D3 compute server

directory: /MMCI/TM/scratch/pebert/diploid_assembly
cores: 46
latency-wait: 5
keep-going: True
rerun-incomplete: True
restart-times: 0