# Default runtime profile for temp. infrastructure / BELINDA

directory: /TM_beegfs/projects/diploid-genome-assembly/pebert
cores: 48
latency-wait: 5
keep-going: True
rerun-incomplete: False
restart-times: 0
resources:
  mem_mb=515072
