# Default runtime profile for temp. infrastructure / UMBRIEL

directory: /TM_beegfs/projects/diploid-genome-assembly/pebert
cores: 32
latency-wait: 5
keep-going: True
rerun-incomplete: True
restart-times: 1
resources:
  mem_mb=902144
