# Default runtime profile for temp. infrastructure / MIRANDA

directory: /TM_beegfs/projects/diploid-genome-assembly/pebert
cores: 64
latency-wait: 5
keep-going: True
rerun-incomplete: False
restart-times: 1
resources:
  mem_mb=257024
