# Default runtime profile for temp. infrastructure / UMBRIEL

directory: /TM_beegfs/projects/diploid-genome-assembly/pebert
cores: 48
latency-wait: 5
keep-going: True
rerun-incomplete: False
restart-times: 1
resources:
  mem_mb=1032192
