# Default runtime profile for TM infrastructure / D3 compute server

directory: /home/pebert/work/projects
cores: 4
latency-wait: 5
keep-going: True
rerun-incomplete: True
restart-times: 0
resources:
  mem_total_mb=4194304
